languages_dict = {
    "en": "English",
    "ne": "Nepali",
    "de": "German",
    "fr": "French",
    "es": "Spanish",
    "ja": "Japanese",
    "ru": "Russian",
    "pt": "Portuguese",
    "it": "Italian",
    "zh": "Chinese",
    "fa": "Persian",
    "pl": "Polish",
    "nl": "Dutch",
    "ar": "Arabic",
    "uk": "Ukrainian",
    "he": "Hebrew",
    "tr": "Turkish",
    "id": "Indonesian",
    "cs": "Czech",
    "sv": "Swedish",
    "ko": "Korean",
    "vi": "Vietnamese",
    "hu": "Hungarian",
    "fi": "Finnish",
    "el": "Greek",
    "no": "Norwegian",
    "hi": "Hindi",
    "ca": "Catalan",
    "th": "Thai",
    "bn": "Bengali",
    "ro": "Romanian",
    "da": "Danish",
    "sr": "Serbian",
    "bg": "Bulgarian",
    "az": "Azerbaijani",
    "ms": "Malay",
    "et": "Estonian",
    "sk": "Slovak",
    "uz": "Uzbek",
    "hy": "Armenian",
    "hr": "Croatian",
    "eu": "Basque",
    "sl": "Slovene",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "kk": "Kazakh",
    "eo": "Esperanto",
    "be": "Belarusian",
    "ta": "Tamil"
}

languages = [
    "en",
    "ne",
    "de",
    "fr",
    "es",
    "ja",
    "ru",
    "pt",
    "it",
    "zh",
    "fa",
    "pl",
    "nl",
    "ar",
    "uk",
    "he",
    "tr",
    "id",
    "cs",
    "sv",
    "ko",
    "vi",
    "hu",
    "fi",
    "el",
    "no",
    "hi",
    "ca",
    "th",
    "bn",
    "ro",
    "da",
    "sr",
    "bg",
    "az",
    "ms",
    "et",
    "sk",
    "uz",
    "hy",
    "hr",
    "eu",
    "sl",
    "lt",
    "lv",
    "kk",
    "eo",
    "be",
    "ta"
]
